### ISSUE TITLE
Build inspect.js failed on MAC OSX

### ISSUE THREAD

**Issue by XiaolinSh** [xiph/aomanalyzer#48]
I tried to build inspect.js on MAC, it failed as follows,
```
Traceback (most recent call last):
  File "/Users/xiaolins/Work/AOM/emsdk-portable/emscripten/1.37.22/em++", line 16, in <module>
    emcc.run()
  File "/Users/xiaolins/Work/AOM/emsdk-portable/emscripten/1.37.22/emcc.py", line 1443, in run
    final = shared.Building.link(linker_inputs, DEFAULT_FINAL, force_archive_contents=force_archive_contents, temp_files=misc_temp_files, just_calculate=just_calculate)
  File "/Users/xiaolins/Work/AOM/emsdk-portable/emscripten/1.37.22/tools/shared.py", line 1772, in link
    Building.read_link_inputs(filter(lambda x: not x.startswith('-'), files))
  File "/Users/xiaolins/Work/AOM/emsdk-portable/emscripten/1.37.22/tools/shared.py", line 1698, in read_link_inputs
    raise Exception('llvm-ar failed on archive ' + archive_names[n] + '!')
Exception: llvm-ar failed on archive /Users/xiaolins/Work/AOM/aom/buildanalyzer/libinspect_1_inspect-post_js.a!
make[3]: *** [examples/inspect.js] Error 1
make[2]: *** [CMakeFiles/inspect.dir/all] Error 2
make[1]: *** [CMakeFiles/inspect.dir/rule] Error 2
make: *** [inspect] Error 2
```

**Comment by mbebenita** [comment]
Interesting, are there any other details about the error? I'm currently using emcc 1.37.19 and I don't have any troubles. I wonder if something has changed.

**Comment by XiaolinSh** [comment]
I verified that emscripten 1.37.19 is worked.

**Comment by kripken** [comment]
I don't see this either (on latest incoming, 1.37.22).

@XiaolinShen , does building from scratch (`rm -rf .inspect` in `tools/`) work? Perhaps an older build's outputs don't mix well with new ones.

If that's not it, perhaps there is something on your system different from ours, like an OS-specific bug. You may be able to bisect on the emscripten repo to find the cause, in that case.
